POST http://localhost:3030/insert HTTP/1.1
Content-Type: application/json

{
    "name" : "Anas AKZAZ",
    "username" : "Anakz",
    "email" : "anasakzaz23@gmail.com",
    "phone": "+212 655 508 814",
    "website": "www.anasakzaz.com",
    "company_name": "Nikola's company"
}

###
DELETE  http://localhost:3030/delete/1 HTTP/1.1
Content-Type: application/json